"""
# Intuition

The sequence generated by repeatedly replacing a number with the sum of the squares of its digits can be viewed as a linked list:

- Each number points to its next value.
- If the number is happy, the sequence eventually reaches `1`.
- Otherwise, the sequence enters a cycle.

Instead of storing all previously seen numbers in a set, we can use Floyd's Cycle Detection Algorithm (Tortoise and Hare) to detect the cycle using constant extra space.

# Approach

1. Define a helper function `getNext()` that computes the sum of the squares of the digits of a number.
2. Initialize:
   - `slow` pointer at `n`
   - `fast` pointer at `getNext(n)`
3. Move:
   - `slow` one step at a time.
   - `fast` two steps at a time.
4. Continue until:
   - `fast` becomes `1`, meaning the number is happy.
   - `slow == fast`, meaning a cycle has been detected.
5. Return `True` if `fast == 1`, otherwise return `False`.

# Complexity

- Time complexity: $$O(k \log n)$$

  Where `k` is the number of generated values before reaching `1` or detecting a cycle. Each transition requires processing all digits of the current number.

- Space complexity: $$O(1)$$

  Only two pointers are maintained regardless of the sequence length.
"""

class Solution:
    def getNext(self, n: int) -> int:
        total = 0

        while n > 0:
            digit = n % 10
            total += digit * digit
            n //= 10

        return total

    def isHappy(self, n: int) -> bool:
        slow = n
        fast = self.getNext(n)

        while fast != 1 and slow != fast:
            slow = self.getNext(slow)
            fast = self.getNext(self.getNext(fast))

        return fast == 1